name: build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x]

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v4

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "yarn"

            # Yarn is included in the list of software installed on the GitHub-hosted Ubuntu
            # so there's no need to include a step install Yarn.

            - name: Install dependencies
              run: yarn

            - name: Check code style
              run: yarn run prettier --config ./.prettierrc.yaml --check  ./src/*

            - name: Build project
              run: yarn build

            - name: Test and generate coverage report
              run: yarn test --watchAll=false --coverage

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v4
              with:
                  name: codecov-umbrella
                  fail_ci_if_error: false
